apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
  namespace: {{ .Values.namespace }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: todoapp
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: app-secrets-volume
          mountPath: "/app/secrets"
          readOnly: true
        - name: app-config-volume
          mountPath: "/app/configs"
          readOnly: true
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        env:
        {{- range Values.secrets }}
        - name: {{ .name }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Chart.Name }}-secret
              key: {{ .name }}
        {{- end }}
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PYTHONUNBUFFERED
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: api/health
            port: 8080
          initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
        readinessProbe:
          httpGet:
            path: api/ready
            port: 8080
          initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.data.name }}
      - name: app-secrets-volume
        secret:
          secretName: app-secret
      - name: app-config-volume
        configMap:
          name: app-config
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: {{ .Values.affinity.nodeAffinity.key }}
                operator: In
                values:
                - {{ .Values.affinity.nodeAffinity.value }}
